version: '3.3'
services:
  app:
    container_name: cars-test-nest
    restart: always
    build: .
    env_file: .env
    ports:
      - '$PORT:$PORT'
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - '27017:27017'
